version: '3'
services:
  mysql5730:
    image: mysql:5.7.30
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: adoccia
    ports:
    - 3306:3306
    volumes:
    - db_data
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql5730
    environment:
      PMA_HOST: mysql5730
    ports:
    - 8080:80
  rabbitmq:
    image: rabbitmq:latest
    volumes:
    - rabbitmq_data:/var/lib/rabbitmq
  rabbitmqctl:
    image: rabbitmq:3.8-management
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - 8888:15672

volumes:
  db_data:
  rabbitmq_data: