version: '3'
services:
  mysql5730:
    image: mysql:5.7.30
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ddc
    ports:
    - 3306:3306
    volumes:
    - ddc_db_data
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql5730
    environment:
      PMA_HOST: mysql5730
    ports:
    - 8080:80
  rabbitmq:
    image: rabbitmq:3.8-management
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  ddc_db_data:
  rabbitmq_data: